### ISSUE TITLE
missing error handling

### ISSUE THREAD

**Issue by cainlevy** [FreedomBen/libmalan#17]
Currently when an endpoint function errors, it throws a superagent error. It's the responsibility of the caller to catch and parse any useful details out of the error. For example:

```typescript
try {
  await whoami(...)
} catch (e) {
  // {
  //   detail: 'Forbidden',
  //   message: 'Anonymous access to this method on this object is not allowed.  You must authenticate and pass a valid token.'
  // }
  e.response.body.errors.detail
}
```

it would be nice if libmalan parsed the common errors itself and threw a more usable error. this error would need to support type narrowing with either a custom prototype (`e instanceof MalanError`) or a type guard (`isMalanError(e)`).

**Comment by FreedomBen** [comment]
Totally agree, and I think that's a great solution!
