### ISSUE TITLE
error type does not match validation errors

### ISSUE THREAD

**Issue by cainlevy** [FreedomBen/libmalan#24]
Validation errors from Malan do not have the `{errors: {detail: string, message: string}}` shape. Instead, they appear to have a shape like `{errors: Record<field, message>}`.

For example:

```
{ errors: { username: [ 'has already been taken' ] } }
```

This information is unfortunately lost in the new error response handling.

**Comment by cainlevy** [comment]
@FreedomBen should this issue be solved in malan or libmalan?

**Comment by FreedomBen** [comment]
Ohhh yeah, you're right!  The default Phoenix handler intercepts those so they bypass the main handler.  I think malan should change so things are consistent.  Let me see how hard it will be to fix. Hopefully it's pretty simple :crossed_fingers:

**Comment by FreedomBen** [comment]
Relates to https://github.com/FreedomBen/malan/issues/99
